# MSM FB
obj-$(CONFIG_FB_MSM) += msm-fb.o
msm-fb-y += msm_fb.o

# MDP
obj-$(CONFIG_FB_MSM_MDP) += msm-mdp.o
msm-mdp-y += mdp4_util.o
msm-mdp-y += mdp4_overlay.o
msm-mdp-y += mdp4_overlay_mddi.o
msm-mdp-y += mdp.o
msm-mdp-y += mdp_cursor.o
msm-mdp-y += mdp_dma.o
msm-mdp-y += mdp_hist.o
msm-mdp-y += mdp_lut.o
msm-mdp-y += mdp_vsync.o

# MDDI
obj-$(CONFIG_FB_MSM_MDDI) += msm-mddi.o
msm-mddi-y += mddi.o
msm-mddi-y += mddihost.o
msm-mddi-y += mddihosti.o
msm-mddi-y += mddi_panel.o
